### PR TITLE
fix long polling slips due to multiple apollo instances would not ins…

### LINKED ISSUE #48: WatchUpdate might be slips in multiple apollo instances
当有多个 apollo server，发布新配置时，客户端可能获取不到最新的配置，并且之后也不会重试。

假设有以下场景：

有 A、B 两个 apollo server，新发布一个配置后，A 率先同步完成，B 正在同步中。此时，如果客户端连接的是 B，便会收到 `GET /notifications/v2` 的通知，进而执行 `GET /configs` 请求获取最新配置。但是 B 还没有同步完成，于是返回了一个 `304 Not Modified` 给客户端。那么客户端便会错过这次更新发布，**更糟糕的是，即便在以后的 Long Polling 中，客户端也无法获得最新的配置**。

本质上是因为客户端在收到 `GET /notifications/v2` 的通知后（拿到了 `NotificationID`），没有正确处理 `GET /configs` 获取的状态，便更新了客户端的 `NotificationID`。导致后续的 `GET /notifications/v2` 请求不会再下发通知，无法触发 `GET /configs` 请求。

相关代码：

https://github.com/philchia/agollo/blob/ef4758d7fe738944cc55110bc7629cdf0872153b/poller.go#L125-L131

L126 的 `handler` 此时返回的是 `nil`，其真正调用的是：

https://github.com/philchia/agollo/blob/ef4758d7fe738944cc55110bc7629cdf0872153b/client.go#L162-L175

L165 此时返回的是两个 `nil`，最简单的修复就是让 `c.requester.request()` 在不是 `200` 时，返回一个 `error`: #49

### PR DESCRIPTION
**Pull request by ms2008**
Fixes #48

### CODE REVIEW

File: request.go [hunk 1]
```diff
@@ -36,5 +37,5 @@ func (r *httprequester) request(url string) ([]byte, error) {
 
 	// Diacard all body if status code is not 200
 	io.Copy(ioutil.Discard, resp.Body)
-	return nil, nil
+	return nil, errors.New("NotHTTPStatusOK: DiscardBody")
```
Comment (philchia) [inline request.go]: 这里可以定义一个 var ErrorStatusNotOK = errors.New("http resp code not ok")
判断错误的时候可以 if err != nil && err != ErrorStatusNotOK

Comment (ms2008) [reply request.go]: 赞同
